jay-bean/Rendering-Routes

.env.example
app.js
auth.js
config/index.js
package-lock.json
package.json
routes/index.js
routes/users.js
routes/utils.js
validations.js
views/index.pug
views/layout.pug
views/user-login.pug
views/user-register.pug
views/utils.pug

- Finished user authentication, and log in.
- Users can now sign up, be stored into the database, and passwords are properly hashed.
- Users can also log in, with proper credentials.
- A user's log in state is also persistent in a session.

User Authentication

---

views/error.pug

Hey guys all I did was comment one a line of code, demonstration purposes.

demonstrating pull request to team

---

app.js
routes/crags.js
routes/index.js
validations.js
views/404.pug
views/all-crags.pug
views/crag.pug
views/new-crag.pug
views/utils.pug

- Added all crag front end routes
- Added respective view files
- Users can now properly submit  a crag post with validation checks
- Users are redirected to their new post upon submission

Crag views and front end routes

---

routes/users.js
views/all-users.pug
views/climb-list.pug
views/user-profile.pug

Working:
- can get all users
- can get individual users

Users and climb lists

---

routes/users.js
views/user-login.pug
views/user-register.pug

- Users now have an option to log in as demo user in the log-in page *and* sign-up page.
- Upon clicking the 'log in as demo user' button, the user is logged in as our test user 'coolGuy48'

Demo user login

---

routes/index.js
views/contact-us.pug
views/index.pug

Found out that we need to do a lot of CSS carousel stuff for the cycling to work.  Leaving these here now for the time being.

Cycle routes

---

routes/crags.js
routes/routes.js
views/crag.pug
views/layout.pug
views/route.pug

'Welcome <username>' username would change when navigating to an individual route page. The name would change to the route post's owners username.

fixed navBar 'welcome user' bug

---

config/database.js
routes/routes.js
routes/users.js
views/route.pug

cragName and a few other things were mistakingly taken out.
fixing that.

Routes edit

---

public/stylesheets/footer.css

Changed text color to white to have better contrast with green background color

changed font color to white for better contrast

---

public/javascripts/climbList.js
public/javascripts/reviews.js
public/javascripts/userEdit.js
routes/users.js
views/user-all-reviews.pug
views/user-profile.pug

Delete for reviews works. Edit reviews is still a work in progress

Review DELETE is done and works

---

public/favicon.ico:Zone.Identifier
public/stylesheets/navbar.css
views/layout.pug

- Added demo user login button to nav bar
- Added Climb List button to nav bar

Nav-bar changes

---

public/stylesheets/climb-list.css
public/stylesheets/main.css
routes/users.js
views/climb-list.pug

Completely styled, and still functional.

Styled climb list page

---

public/stylesheets/contact-us.css
public/stylesheets/footer.css
views/contact-us.pug
views/layout.pug

- Contact us page styled
- Footer Styled
- Navbar 'people' changed to 'community'

Contact-Us styling and footer

---

auth.js
public/javascripts/routeEdit.js
routes/routes.js
routes/users.js

All console.log and console.error lines are commented out

combed through files for console.logs

---

public/javascripts/reviews.js
public/stylesheets/route.css
views/route.pug

fixed broken image on non-image routes, and fixed DOM manipulated rev…

Fixed reviews

---

public/javascripts/climbList.js
public/javascripts/routeEdit.js
public/stylesheets/index.css
public/stylesheets/route.css
public/stylesheets/routes.css
public/stylesheets/sign-up.css
routes/routes.js
views/route.pug
views/routes.pug

finished route edit form.
changed climb list event listener to hide climb-list-p tag, looks better for the user now.

Final functionality

---

public/stylesheets/new-crag.css
public/stylesheets/route-add.css
views/new-crag.pug
views/route-add.pug

let me know if something doesn't work!

Add route styling - DONE!

---

public/javascripts/climbList.js
public/stylesheets/index.css
public/stylesheets/new-crag.css
public/stylesheets/route.css
routes/crags.js
routes/index.js
views/index.pug
views/new-crag.pug
views/reviews.pug
views/route.pug

- Styled home page
- Fixed a few console log errors
- Fixed images being stretched on individual route pages

Home page styling

---

public/javascripts/reviews.js
public/stylesheets/main.css
public/stylesheets/route.css
public/stylesheets/user-all-reviews.css
routes/routes.js
validations.js
views/reviews.pug
views/route-add.pug
views/user-all-reviews.pug

fixed add route bug.
finished styling reviews page.
found a bug in users review page -- when you press edit and then submit your review it works. if you press edit again we get a null error. the form becomes null for some reason. could not figure out the bug.

Styling user reviews page

---

public/stylesheets/community.css
public/stylesheets/main.css
views/all-users.pug

community page styled.
feel free to make any changes if you want!

community page styled

---

routes/routes.js
views/all-users.pug
views/reviews.pug

fixed username bug. reviews were showing the route owner owned the review and not myself.

Styling community page

---

public/stylesheets/crag.css
views/crag.pug

Crag views

---

public/javascripts/reviews.js
public/stylesheets/route.css
routes/routes.js
views/all-users.pug
views/reviews.pug
views/user-all-reviews.pug

stars working for reviews on route page

Star trial

---

public/stylesheets/route.css
views/route.pug

fixed climb list add bug on route page

fixed climb list bug on route page
